[package]
name = "merkle-log"
version = "0.0.3"
authors = ["sunny-g <sunny.gonna@gmail.com>"]
description = "An implementation of the \"Merkle Tree-Structured Log\" defined in the paper \"Transparent Logs for Skeptical Clients.\" https://research.swtch.com/tlog"
repository = "https://github.com/sunny-g/merkle-log"
documentation = "https://docs.rs/merkle-log"
keywords = ["merkle-tree", "crypto"]
categories = ["cryptography", "data-structures"]
license = "MIT OR Apache-2.0"
edition = "2018"

[dependencies]
anyhow = "1.0.36"
async-trait = "0.1.42"
digest = "0.9"
serde = { version = "1.0", features = ["derive"], optional = true }
thiserror = "1.0.22"

[dev-dependencies]
async-std = { version = "1.8.0", features = ["attributes"] }
sha2 = "0.9"
